### ISSUE TITLE
the encode image feature  is nan 

### ISSUE THREAD

**Issue by RNGrunshen** [ABaldrati/CLIP4CirDemo#2]
when I run extract_features.py，I found the elements of batch_features are all nan:
``` python
batch_features = clip_model.encode_image(images)
```
**result:** `tensor([[nan, nan, nan ....nan, nan]]`
then I use the code below to test. When I load RN50x4 model, the result is the same as above(both wild image and dataset image). But when I load another model like ViT-B/32, the result is not nan:
``` python
import clip
import torch
import PIL.Image
import PIL.ImageOps
from data_utils import targetpad_transform, server_base_path

if torch.cuda.is_available():
    device = torch.device("cuda")
    data_type = torch.float16
else:
    device = torch.device("cpu")
    data_type = torch.float32

#RN50x4
#"ViT-B/32"
clip_model, clip_preprocess = clip.load("RN50x4")
clip_model = clip_model.eval().to(device)

image_path = 'woman.jpg'
pil_image = PIL.Image.open(image_path).convert('RGB')
image = targetpad_transform(1.25, clip_model.visual.input_resolution)(pil_image).to(device)
reference_features = clip_model.encode_image(image.unsqueeze(0))
```
I would like to know how to solve this problem? And I would appreciate it if you could test it and tell me the solution.

**Comment by RNGrunshen** [comment]
I change my

> when I run extract_features.py，I found the elements of batch_features are all nan:
> 
> ```python
> batch_features = clip_model.encode_image(images)
> ```
> 
> **result:** `tensor([[nan, nan, nan ....nan, nan]]` then I use the code below to test. When I load RN50x4 model, the result is the same as above(both wild image and dataset image). But when I load another model like ViT-B/32, the result is not nan:
> 
> ```python
> import clip
> import torch
> import PIL.Image
> import PIL.ImageOps
> from data_utils import targetpad_transform, server_base_path
> 
> if torch.cuda.is_available():
>     device = torch.device("cuda")
>     data_type = torch.float16
> else:
>     device = torch.device("cpu")
>     data_type = torch.float32
> 
> #RN50x4
> #"ViT-B/32"
> clip_model, clip_preprocess = clip.load("RN50x4")
> clip_model = clip_model.eval().to(device)
> 
> image_path = 'woman.jpg'
> pil_image = PIL.Image.open(image_path).convert('RGB')
> image = targetpad_transform(1.25, clip_model.visual.input_resolution)(pil_image).to(device)
> reference_features = clip_model.encode_image(image.unsqueeze(0))
> ```
> 
> I would like to know how to solve this problem? And I would appreciate it if you could test it and tell me the solution.

I change my computer and solve the problem.....

**Comment by Wang-XingHao** [comment]
Hello, I also met the exactly same question you mentioned above, but my device is limited, so I tried to change the model to "ViT-B/32", and there's another problem
`Traceback (most recent call last):
  File "D:\anaconda\lib\site-packages\flask\app.py", line 2528, in wsgi_app
    response = self.full_dispatch_request()
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1825, in full_dispatch_request
    rv = self.handle_user_exception(e)
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1823, in full_dispatch_request
    rv = self.dispatch_request()
  File "D:\anaconda\lib\site-packages\flask\app.py", line 1799, in dispatch_request
    return self.ensure_sync(self.view_functions[rule.endpoint])(**view_args)
  File "D:CLIP4CirDemo-main\app.py", line 156, in results
    sorted_group_names, sorted_index_names, target_name = compute_cirr_results(caption, combiner, n_retrieved,
  File "D:CLIP4CirDemo-main\app.py", line 295, in compute_cirr_results
    predicted_features = combiner.combine_features(reference_features, text_features).squeeze(0)
RuntimeError: The following operation failed in the TorchScript interpreter.
Traceback of TorchScript (most recent call last):
  File "D:CLIP4CirDemo-main\model.py", line 42, in combine_features
        :return: predicted features
        """
        text_projected_features = self.dropout1(F.relu(self.text_projection_layer(text_features)))
                                                       ~~~~~~~~~~~~~~~~~~~~~~~~~~ <--- HERE
        image_projected_features = self.dropout2(F.relu(self.image_projection_layer(image_features)))
    
  File "D:\anaconda\lib\site-packages\torch\nn\modules\linear.py", line 114, in forward
    def forward(self, input: Tensor) -> Tensor:
        return F.linear(input, self.weight, self.bias)
               ~~~~~~~~ <--- HERE
RuntimeError: mat1 and mat2 shapes cannot be multiplied (1x512 and 640x2560)
`
It seems like after changing the model, something went wrong with the feature dimension, but I'm new in this area and have no ideas about how to solve this problem. Have you ever tried to run the demo with "ViT-B/32" model? I really need some help here, or could you please share the correct features file extracted by the "RN50x4" model? My e-mail is 1395252624@qq.com I would really appreciate it if you can help me, thanks for your time.
