### ISSUE TITLE
no full fashion dataset available?

### ISSUE THREAD

**Issue by KosarKeshavarz** [ABaldrati/CLIP4CirDemo#3]
hello. As mentioned in the paper you used the original fashionIQ dataset containing around 77000 images. but there are many missing images in the current dataset (from the main GitHub page for the dataset and also other sources). do you have access to the full dataset? I would appreciate it if you share the whole dataset to be used in future works.

**Comment by ABaldrati** [comment]
Hi @KosarKeshavarz 

I think you can download the FashionIQ dataset using the link in [the following issue.](https://github.com/XiaoxiaoGuo/fashion-iq/issues/18)

Best, Alberto

**Comment by complete-dope** [comment]
@ABaldrati The fashioniq dataset link is broken could you please provide an updated link?

**Comment by luna-forever** [comment]
> Hi @KosarKeshavarz
> 
> I think you can download the FashionIQ dataset using the link in [the following issue.](https://github.com/XiaoxiaoGuo/fashion-iq/issues/18)
> 
> Best, Alberto

hello,I used the dataset provided in this link and the run still shows missing images. Can you provide the Fashion IQ dataset you used? I really need it, thanks.
